markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: http://pinderpeng.github.io
author: Pinder
pygments: true
safe: true
paginate: 16
auto: true
duoshuo: pinder
email: pinderpeng at gmail dot com
